language: node-js
os:
  - linux
  - osx
node_js:
  - "node"
before-install:
  - npm install -g npm@latest
install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install fakeroot; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install rpm; fi
  - npm install -g gulp-cli
  - pushd ./src/Sfx
  - npm install
  - popd
  - pushd ./src/Sfx-Standalone
  - npm install
  - popd
script:
  - gulp -f ./src/Sfx/gulpfile.js clean-build
  - gulp -f ./src/Sfx-Standalone/gulpfile.js publish
